### PR TITLE
Add controller/node statistics to model

### PR DESCRIPTION
**Pull request by raman325**
See https://github.com/zwave-js/zwave-js-server/pull/296 

We will now be receiving an initial state of statistics for the node and controller and will receive regular updates to those statistics from the `statistics updated` event

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
There's a merge conflict.

**Review by MartinHjelmare — APPROVED** [review]
This is backwards compatible with servers that don't support the new statistics updated event yet, right?

**Comment by MartinHjelmare** [comment]
We should remember to require schema 7 as minimum version here in the library when we want to start using this feature in the integration.

**Comment by raman325** [comment]
> This is backwards compatible with servers that don't support the new statistics updated event yet, right?

yes it is which is why I didn't bump schemas here although I should have set max to 7. The other PR for the new endpoint commands does require 7 so I will bump the minimum in that one before merging

**Pull request merged**
