### PR TITLE
Support get_raw_config_parameter_value

### PR DESCRIPTION
**Pull request by MindFreeze**
Needed for certification.
Related PR in the JS server https://github.com/zwave-js/zwave-js-server/pull/1300

### CODE REVIEW

**Review by MartinHjelmare — APPROVED** [review]
Looks good!

Can be merged when the server PR is merged and we've bumped the minimum schema version.

**Comment by MindFreeze** [comment]
Server PR merged an in 1.39.0

**Comment by MartinHjelmare** [comment]
https://github.com/zwave-js/zwave-js-server/pull/1300#discussion_r1804509223

**Comment by MartinHjelmare** [comment]
Before we can use the new commands we either need to specify the minimum schema version in the command signature for each new command or bump the minimum schema version in the client.

**Comment by MindFreeze** [comment]
@MartinHjelmare I set `require_schema: 39` for the command. Should I bump MAX_SERVER_SCHEMA_VERSION in this PR?

**Comment by MartinHjelmare** [comment]
Yes, please bump the max version.

**Review by MartinHjelmare — APPROVED** [review]
Thanks!

**Pull request merged**
