### PR TITLE
Fix typehint for Value Metadata states

### PR DESCRIPTION
**Pull request by raman325**
The below issues are happening because of this PR: https://github.com/zwave-js/node-zwave-js/pull/5792

Even though the original state keys are numeric, they are represented as strings so we should fix that typehint as well

Fixes https://github.com/home-assistant/core/issues/93252
Fixes https://github.com/home-assistant/core/issues/93299

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Is this backwards compatible?

**Comment by raman325** [comment]
It should be as our tests pass. Just to be sure, I changed the typehint from `dict[str | bool, str]` to `dict[None, str]` and three tests failed. If we want to be safe we can add `int` as a typehint but the state key has always been a string representation of the int as far as I have seen

**Comment by MartinHjelmare** [comment]
Should we add a test with the metadata in the reported issues?

**Comment by raman325** [comment]
> Should we add a test with the metadata in the reported issues?

done

**Review by MartinHjelmare — APPROVED** [review]

**Pull request merged**
