### PR TITLE
Add constants for Humidity Control CCs

### PR DESCRIPTION
**Pull request by EiNSTeiN-**
This PR adds the constants that are necessary to use the Humidity Control CCs which are added by https://github.com/zwave-js/node-zwave-js/pull/4048

### CODE REVIEW

**Comment by firstof9** [comment]
I think tests will be required prior to merging. Just fyi.

**Comment by EiNSTeiN-** [comment]
This PR is adding constants, how are these tested for other CCs? I don't see any tests for e.g. `zwave_js_server/const/command_class/thermostat.py`

**Comment by firstof9** [comment]
Oops, it was a quick glance. :+1:

**Review by raman325 — APPROVED** [review]
thanks!

**Pull request merged**
