### PR TITLE
Add functionality to record messages between lib and server

### PR DESCRIPTION
**Pull request by raman325**
Here's my proposal for how we will record messages. My current best idea for how to implement this in HA is:
Add a UI control somewhere that, when clicked, reloads the integration but sets `record_messages` to `True` in the client initialization. We can detect whether or not the record message functionality is enabled and display a different UI control in the same place to allow the user stop the recording and download the recording once they are done trying to repro their given issue.

As a bonus, we could offer a mechanism in the UI control to allow the user to either reload the config entry to watch everything from startup or just record from that moment onwards depending on the use case (the implementation supports both)

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Could we reuse the dump feature we already have for this purpose? It allows keeping the connection open for a timeout.

**Comment by raman325** [comment]
> Could we reuse the dump feature we already have for this purpose? It allows keeping the connection open for a timeout.
> 
> https://github.com/home-assistant-libs/zwave-js-server-python/blob/7b0c9e4c5819ffc3eb3d35bbc829a546eb56d6d6/zwave_js_server/dump.py#L10-L15

You want to use the same client as the integration uses so that you can see the commands being sent and the responses coming from the server, right? I don't think it makes sense to embed this in the dump logic then

**Comment by MartinHjelmare** [comment]
Yeah, I guess a second client won't see the messages we send from the first client, event if all messages sent from the server are seen by both clients.

**Review by MartinHjelmare — APPROVED** [review]
Looks good!

**Pull request merged**
