### PR TITLE
Add codecov

### LINKED ISSUE #88: Add codecov service and action
- We want to keep track of coverage and make sure that new code is tested.

### PR DESCRIPTION
**Pull request by MartinHjelmare**
- Set minimum coverage ratio for a commit to 90 %.
- Allow some (0.09 %) coverage drop.

fixes #88

### CODE REVIEW

**Comment by frenck** [comment]
`Issue detecting commit SHA. Please run actions/checkout with fetch-depth > 1 or set to 0`

**Comment by MartinHjelmare** [comment]
I think that's because there's no base report yet. I don't think it matters for the 403 error.

**Comment by MartinHjelmare** [comment]
Bumping checkout to see if that helps.

**Comment by MartinHjelmare** [comment]
Codecov upload succeeded now.

**Review by frenck — APPROVED** [review]

**Pull request merged**
